[2024-02-25T11:22:49.659+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: processing_sales.load_data_to_bronze scheduled__2022-08-01T01:00:00+00:00 [queued]>
[2024-02-25T11:22:49.666+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: processing_sales.load_data_to_bronze scheduled__2022-08-01T01:00:00+00:00 [queued]>
[2024-02-25T11:22:49.667+0000] {taskinstance.py:2171} INFO - Starting attempt 23 of 26
[2024-02-25T11:22:49.679+0000] {taskinstance.py:2192} INFO - Executing <Task(GCSToBigQueryOperator): load_data_to_bronze> on 2022-08-01 01:00:00+00:00
[2024-02-25T11:22:49.683+0000] {standard_task_runner.py:60} INFO - Started process 323 to run task
[2024-02-25T11:22:49.686+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'processing_sales', 'load_data_to_bronze', 'scheduled__2022-08-01T01:00:00+00:00', '--job-id', '107', '--raw', '--subdir', 'DAGS_FOLDER/process_sales.py', '--cfg-path', '/tmp/tmp8smj_02p']
[2024-02-25T11:22:49.687+0000] {standard_task_runner.py:88} INFO - Job 107: Subtask load_data_to_bronze
[2024-02-25T11:22:49.732+0000] {task_command.py:423} INFO - Running <TaskInstance: processing_sales.load_data_to_bronze scheduled__2022-08-01T01:00:00+00:00 [running]> on host 9e4f31030bba
[2024-02-25T11:22:49.800+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='processing_sales' AIRFLOW_CTX_TASK_ID='load_data_to_bronze' AIRFLOW_CTX_EXECUTION_DATE='2022-08-01T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='23' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-08-01T01:00:00+00:00'
[2024-02-25T11:22:49.810+0000] {connection.py:234} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-02-25T11:22:49.814+0000] {base.py:83} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-02-25T11:22:49.815+0000] {gcs_to_bigquery.py:379} INFO - Using existing BigQuery table for storing data...
[2024-02-25T11:22:49.852+0000] {gcs_to_bigquery.py:383} INFO - Executing: {'load': {'autodetect': True, 'createDisposition': 'CREATE_IF_NEEDED', 'destinationTable': {'projectId': 'de-07-natalia-sokil', 'datasetId': 'bronze', 'tableId': 'sales'}, 'sourceFormat': 'CSV', 'sourceUris': ['gs://sokil_final_project/data/sales/2022-08-01/*.csv'], 'writeDisposition': 'WRITE_APPEND', 'ignoreUnknownValues': False, 'schema': {'fields': [{'name': 'CustomerId', 'type': 'STRING', 'mode': 'NULLABLE'}, {'name': 'PurchaseDate', 'type': 'STRING', 'mode': 'NULLABLE'}, {'name': 'Product', 'type': 'STRING', 'mode': 'NULLABLE'}, {'name': 'Price', 'type': 'STRING', 'mode': 'NULLABLE'}]}, 'skipLeadingRows': 1, 'fieldDelimiter': ',', 'quote': None, 'allowQuotedNewlines': False, 'encoding': 'UTF-8'}}
[2024-02-25T11:22:49.854+0000] {bigquery.py:1596} INFO - Inserting job ***_processing_sales_load_data_to_bronze_2022_08_01T01_00_00_00_00_01be3f38ca885e802bef72a55e543dfd
[2024-02-25T11:22:50.621+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 442, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py", line 952, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.NotFound: 404 Not found: Uris gs://sokil_final_project/data/sales/2022-08-01/*.csv
[2024-02-25T11:22:50.629+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=processing_sales, task_id=load_data_to_bronze, execution_date=20220801T010000, start_date=20240225T112249, end_date=20240225T112250
[2024-02-25T11:22:50.641+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 107 for task load_data_to_bronze (404 Not found: Uris gs://sokil_final_project/data/sales/2022-08-01/*.csv; 323)
[2024-02-25T11:22:50.661+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-25T11:22:50.690+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
