[2024-02-25T11:20:38.468+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: processing_sales.load_data_to_bronze scheduled__2022-08-01T01:00:00+00:00 [queued]>
[2024-02-25T11:20:38.477+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: processing_sales.load_data_to_bronze scheduled__2022-08-01T01:00:00+00:00 [queued]>
[2024-02-25T11:20:38.477+0000] {taskinstance.py:2171} INFO - Starting attempt 22 of 25
[2024-02-25T11:20:38.488+0000] {taskinstance.py:2192} INFO - Executing <Task(GCSToBigQueryOperator): load_data_to_bronze> on 2022-08-01 01:00:00+00:00
[2024-02-25T11:20:38.493+0000] {standard_task_runner.py:60} INFO - Started process 280 to run task
[2024-02-25T11:20:38.496+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'processing_sales', 'load_data_to_bronze', 'scheduled__2022-08-01T01:00:00+00:00', '--job-id', '106', '--raw', '--subdir', 'DAGS_FOLDER/process_sales.py', '--cfg-path', '/tmp/tmpgak86bcy']
[2024-02-25T11:20:38.497+0000] {standard_task_runner.py:88} INFO - Job 106: Subtask load_data_to_bronze
[2024-02-25T11:20:38.539+0000] {task_command.py:423} INFO - Running <TaskInstance: processing_sales.load_data_to_bronze scheduled__2022-08-01T01:00:00+00:00 [running]> on host 9e4f31030bba
[2024-02-25T11:20:38.598+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='processing_sales' AIRFLOW_CTX_TASK_ID='load_data_to_bronze' AIRFLOW_CTX_EXECUTION_DATE='2022-08-01T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='22' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-08-01T01:00:00+00:00'
[2024-02-25T11:20:38.608+0000] {connection.py:234} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-02-25T11:20:38.611+0000] {base.py:83} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-02-25T11:20:38.612+0000] {gcs_to_bigquery.py:379} INFO - Using existing BigQuery table for storing data...
[2024-02-25T11:20:38.649+0000] {gcs_to_bigquery.py:383} INFO - Executing: {'load': {'autodetect': True, 'createDisposition': 'CREATE_IF_NEEDED', 'destinationTable': {'projectId': 'de-07-natalia-sokil', 'datasetId': 'bronze', 'tableId': 'sales'}, 'sourceFormat': 'CSV', 'sourceUris': ['gs://sokil_final_project/data/sales/2022-08-01/*.csv'], 'writeDisposition': 'WRITE_APPEND', 'ignoreUnknownValues': False, 'schema': {'fields': [{'name': 'CustomerId', 'type': 'STRING', 'mode': 'NULLABLE'}, {'name': 'PurchaseDate', 'type': 'STRING', 'mode': 'NULLABLE'}, {'name': 'Product', 'type': 'STRING', 'mode': 'NULLABLE'}, {'name': 'Price', 'type': 'STRING', 'mode': 'NULLABLE'}]}, 'skipLeadingRows': 1, 'fieldDelimiter': ',', 'quote': None, 'allowQuotedNewlines': False, 'encoding': 'UTF-8'}}
[2024-02-25T11:20:38.650+0000] {bigquery.py:1596} INFO - Inserting job ***_processing_sales_load_data_to_bronze_2022_08_01T01_00_00_00_00_9b91300a926c85b8d8c58b70523177c0
[2024-02-25T11:20:39.396+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 442, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py", line 952, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.Forbidden: 403 Access Denied: File gs://sokil_final_project/data/sales/2022-08-01/: Access Denied
[2024-02-25T11:20:39.403+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=processing_sales, task_id=load_data_to_bronze, execution_date=20220801T010000, start_date=20240225T112038, end_date=20240225T112039
[2024-02-25T11:20:39.414+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 106 for task load_data_to_bronze (403 Access Denied: File gs://sokil_final_project/data/sales/2022-08-01/: Access Denied; 280)
[2024-02-25T11:20:39.431+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-25T11:20:39.451+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
